# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.CharField(max_length=255)),
                ('grantedDesc', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grantedLikes', models.ManyToManyField(related_name='user_likes', to='login.User')),
            ],
        ),
    ]
