# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_auto_20180924_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granted',
            name='grantedLikes',
            field=models.ManyToManyField(default='0', related_name='user_likes', to='login.User'),
        ),
    ]
